# Default initial positions for robot's ros2_control fake system

initial_positions:
  finger_1_joint: 0
  finger_2_joint: 0
  robot_arm_base_turn: 0
  robot_arm_down_joint: 0
  robot_arm_front_joint: 0
  robot_arm_turn_joint: 3.14
  robot_arm_up_joint: 0.8
  robot_hand_joint: 0
